spring:
  datasource:
    username: book_reviews
    password: book_reviews
    url: jdbc:mysql://localhost:3306/book_reviews
    
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    
  sql:
    init:
      mode: always